from typing import Protocol


class Transport(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def read_frame(self) -> bytes: ...
    async def write_frame(self, data: bytes) -> None: ...
